BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "auraapps"
BBFILE_PATTERN_auraapps = "^${LAYERDIR}/"
BBFILE_PRIORITY_auraapps = "7"

LAYERVERSION_auraapps = "1"
LAYERDEPENDS_auraapps = "core ce1113"
LAYERSERIES_COMPAT_auraapps = "scarthgap"
