# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/jecampos/poky-scarthgap-5.0.19/meta \
  /home/jecampos/poky-scarthgap-5.0.19/meta-poky \
  /home/jecampos/poky-scarthgap-5.0.19/meta-yocto-bsp \
  /home/jecampos/CE1113_P1/meta-aurabot \
  "
