# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-aurabot"
BBFILE_PATTERN_meta-aurabot = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-aurabot = "6"

LAYERDEPENDS_meta-aurabot = "core"
LAYERSERIES_COMPAT_meta-aurabot = "scarthgap"
