# Añadir la carpeta de la capa al BBPATH
BBPATH .= ":${LAYERDIR}"

# Añadir las recetas (.bb y .bbappend) a BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

# Nombre de la colección para esta capa
BBFILE_COLLECTIONS += "ce1113"
BBFILE_PATTERN_ce1113 = "^${LAYERDIR}/"
# Prioridad estándar (6 es la de por defecto en meta-oe)
BBFILE_PRIORITY_ce1113 = "6"

# Dependencias (dependemos de la capa core de Poky)
LAYERDEPENDS_ce1113 = "core"

# Compatibilidad con Yocto 5.0 (Scarthgap)
LAYERSERIES_COMPAT_ce1113 = "scarthgap"
