BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "server"
BBFILE_PATTERN_server = "^${LAYERDIR}/"
BBFILE_PRIORITY_server = "7"

LAYERVERSION_server = "1"

LAYERDEPENDS_server = "core ce1113"

LAYERSERIES_COMPAT_server = "scarthgap"