BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "red"
BBFILE_PATTERN_red = "^${LAYERDIR}/"
BBFILE_PRIORITY_red = "6"

LAYERVERSION_red = "1"
LAYERDEPENDS_red = "core ce1113 raspberrypi"
LAYERSERIES_COMPAT_red = "scarthgap"
