BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "operaciones"
BBFILE_PATTERN_operaciones = "^${LAYERDIR}/"
BBFILE_PRIORITY_operaciones = "7"

# Dependemos del core y opcionalmente de nuestra capa base
LAYERDEPENDS_operaciones = "core ce1113"
LAYERSERIES_COMPAT_operaciones = "scarthgap"
