#ifndef AURABOT_HARDWARE_CONFIG_H
#define AURABOT_HARDWARE_CONFIG_H

/* Estos valores deben sustituirse por los pines BCM verificados en el robot. */
#ifndef AURABOT_LEFT_PWM_PIN
#define AURABOT_LEFT_PWM_PIN (-1)
#endif
#ifndef AURABOT_LEFT_IN1_PIN
#define AURABOT_LEFT_IN1_PIN (-1)
#endif
#ifndef AURABOT_LEFT_IN2_PIN
#define AURABOT_LEFT_IN2_PIN (-1)
#endif
#ifndef AURABOT_RIGHT_PWM_PIN
#define AURABOT_RIGHT_PWM_PIN (-1)
#endif
#ifndef AURABOT_RIGHT_IN1_PIN
#define AURABOT_RIGHT_IN1_PIN (-1)
#endif
#ifndef AURABOT_RIGHT_IN2_PIN
#define AURABOT_RIGHT_IN2_PIN (-1)
#endif
#ifndef AURABOT_LEFT_SENSOR_PIN
#define AURABOT_LEFT_SENSOR_PIN (-1)
#endif
#ifndef AURABOT_RIGHT_SENSOR_PIN
#define AURABOT_RIGHT_SENSOR_PIN (-1)
#endif
#ifndef AURABOT_LEFT_ENCODER_PIN
#define AURABOT_LEFT_ENCODER_PIN (-1)
#endif
#ifndef AURABOT_RIGHT_ENCODER_PIN
#define AURABOT_RIGHT_ENCODER_PIN (-1)
#endif
#ifndef AURABOT_LED_POWER_PIN
#define AURABOT_LED_POWER_PIN (-1)
#endif
#ifndef AURABOT_LED_MANUAL_PIN
#define AURABOT_LED_MANUAL_PIN (-1)
#endif
#ifndef AURABOT_LED_AUTO_PIN
#define AURABOT_LED_AUTO_PIN (-1)
#endif
#ifndef AURABOT_LED_OBSTACLE_PIN
#define AURABOT_LED_OBSTACLE_PIN (-1)
#endif

#define AURABOT_SENSOR_ACTIVE_LOW 0
#define AURABOT_LED_ACTIVE_HIGH 1
#define AURABOT_PWM_FREQUENCY_HZ 100
#define AURABOT_ENCODER_POLL_US 1000
#define AURABOT_LEFT_TICKS_PER_REVOLUTION 35U
#define AURABOT_RIGHT_TICKS_PER_REVOLUTION 35U
#define AURABOT_LEFT_WHEEL_CIRCUMFERENCE_MM 204U
#define AURABOT_RIGHT_WHEEL_CIRCUMFERENCE_MM 204U
#define AURABOT_WHEEL_BASE_MM 160U

#endif
